# Generated by Django 5.2.17 on 2026-09-10 11:39

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtorfollowup',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=core.storage.private_document_storage, upload_to='credit_control/followups/debtors/'),
        ),
    ]
