# Generated by Django 5.2.6 on 2026-08-04 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_taskactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocked_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasktimeentry',
            name='entry_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('FOCUS', 'Focus mode')], default='MANUAL', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('due_time__isnull', True), ('due_date__isnull', False), _connector='OR'), name='tasker_task_time_requires_date'),
        ),
        migrations.AddConstraint(
            model_name='tasktimeentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duration__isnull', True), ('ended_at__isnull', True)), models.Q(('duration__isnull', False), ('ended_at__isnull', False)), _connector='OR'), name='tasker_time_end_duration_pair'),
        ),
        migrations.AddConstraint(
            model_name='tasktimeentry',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('is_deleted', False)), fields=('user',), name='tasker_one_running_timer_user'),
        ),
    ]
