# Generated by Django 5.2.6 on 2026-08-04 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_task_blocked_reason_tasktimeentry_entry_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasker_daily_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
