# Generated by Django 5.2.6 on 2026-08-04 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0006_seed_ai_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aiconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('max_output_tokens__gte', 1)), name='tasker_ai_cfg_tokens_pos'),
        ),
        migrations.AddConstraint(
            model_name='aiconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('timeout_seconds__gte', 1)), name='tasker_ai_cfg_timeout_pos'),
        ),
        migrations.AddConstraint(
            model_name='aiconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('max_retries__lte', 10)), name='tasker_ai_cfg_retries_max'),
        ),
        migrations.AddConstraint(
            model_name='aiconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('temperature__isnull', True), models.Q(('temperature__gte', 0), ('temperature__lte', 2)), _connector='OR'), name='tasker_ai_cfg_temp_range'),
        ),
        migrations.AddConstraint(
            model_name='aiconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('daily_request_limit__gte', 1), ('daily_token_limit__gte', 1), ('requests_per_minute__gte', 1)), name='tasker_ai_cfg_limits_pos'),
        ),
        migrations.AddConstraint(
            model_name='aifeedback',
            constraint=models.CheckConstraint(condition=models.Q(('rating__in', (-1, 1))), name='tasker_ai_feedback_rating'),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='tasker_prompt_version_pos'),
        ),
    ]
