# Generated by Django 5.2.6 on 2026-08-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0007_aiconfiguration_tasker_ai_cfg_tokens_pos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='reasoning_effort',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('xhigh', 'Extra high')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='response_verbosity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
