# Generated by Django 5.2.17 on 2026-09-10 11:39

import core.storage
import tasker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0009_seed_personal_assistant_prompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storage.private_document_storage, upload_to=tasker.models.task_attachment_path),
        ),
    ]
