# Generated by Django 5.2.6 on 2025-09-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True),
        ),
    ]
