# Generated by Django 5.2.6 on 2025-09-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_reorder_level_product_reserved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
