# Generated by Django 5.2.6 on 2025-12-31 14:26

import django.core.validators
import django.db.models.deletion
import inventory.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_combo_comboitem'),
        ('sales', '0005_remove_comboitem_combo_alter_documentline_combo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tracking_mode',
            field=models.CharField(choices=[('QUANTITY', 'Quantity'), ('SERIAL', 'Serial Numbers')], default='QUANTITY', max_length=10),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('origin_country', models.CharField(max_length=80)),
                ('destination_country', models.CharField(max_length=80)),
                ('incoterm', models.CharField(choices=[('FOB', 'FOB'), ('CIF', 'CIF'), ('EXW', 'EXW')], max_length=5)),
                ('shipping_method', models.CharField(choices=[('SEA', 'Sea'), ('AIR', 'Air'), ('ROAD', 'Road')], max_length=10)),
                ('eta_date', models.DateField(blank=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('IN_TRANSIT', 'In transit'), ('ARRIVED', 'Arrived'), ('CLEARED', 'Cleared'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed')], default='CREATED', max_length=12)),
                ('allocation_basis', models.CharField(choices=[('VALUE', 'Value'), ('QUANTITY', 'Quantity')], default='VALUE', max_length=10)),
                ('base_currency', models.CharField(default=inventory.models.default_currency_code, max_length=5)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('landed_cost_allocated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_created', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_received', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('FREIGHT', 'Freight'), ('DUTY', 'Duty'), ('VAT', 'VAT'), ('CLEARING', 'Clearing'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], max_length=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default=inventory.models.default_currency_code, max_length=5)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('amount_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('allocated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='inventory.shipment')),
            ],
            options={
                'ordering': ['shipment', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STATUS', 'Status'), ('COST', 'Cost Allocation'), ('RECEIPT', 'Receipt')], default='STATUS', max_length=10)),
                ('previous_status', models.CharField(blank=True, choices=[('CREATED', 'Created'), ('IN_TRANSIT', 'In transit'), ('ARRIVED', 'Arrived'), ('CLEARED', 'Cleared'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed')], max_length=12)),
                ('new_status', models.CharField(blank=True, choices=[('CREATED', 'Created'), ('IN_TRANSIT', 'In transit'), ('ARRIVED', 'Arrived'), ('CLEARED', 'Cleared'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_expected', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('unit_purchase_price', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('hs_code', models.CharField(blank=True, max_length=50)),
                ('tracking_mode', models.CharField(choices=[('QUANTITY', 'Quantity'), ('SERIAL', 'Serial Numbers')], default='QUANTITY', max_length=10)),
                ('landed_unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('landed_total_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='inventory.product')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.shipment')),
            ],
            options={
                'ordering': ['shipment', 'product__name'],
                'unique_together': {('shipment', 'product', 'hs_code')},
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=120, unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('landed_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('FAULTY', 'Faulty'), ('RETURNED', 'Returned')], default='AVAILABLE', max_length=12)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('fault_reported_at', models.DateTimeField(blank=True, null=True)),
                ('fault_notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_units_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.product')),
                ('sale_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_units', to='sales.documentline')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.shipment')),
                ('shipment_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.shipmentitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['serial_number'], name='inventory_p_serial__10e472_idx'), models.Index(fields=['product', 'status'], name='inventory_p_product_cd764a_idx')],
            },
        ),
    ]
