# Generated by Django 5.2.6 on 2026-01-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_tracking_mode_shipment_shipmentcost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
