# Generated by Django 5.2.6 on 2026-01-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_shipment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentcost',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='shipment_costs/%Y/%m/'),
        ),
    ]
