# Generated by Django 5.2.17 on 2026-09-10 11:39

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_stockmovement_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentcost',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, storage=core.storage.private_document_storage, upload_to='shipment_costs/%Y/%m/'),
        ),
    ]
