# Generated by Django 5.2.17 on 2026-09-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_shipmentcost_supporting_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.CharField(blank=True, choices=[('printing', 'Printing & Business Equipment'), ('fitness', 'Boforg Home Fitness')], db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='combo',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Publish this package in the shop after reviewing its components and description.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Show in the public shop. Hide internal charges here.'),
        ),
        migrations.AddField(
            model_name='product',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
