# Generated by Django 5.2.17 on 2026-09-10 17:38

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_category_department_combo_is_public_and_more'),
    ]

    operations = [
        # Shared extension: remove our indexes on rollback, never drop an extension
        # which another application may also use.
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS pg_trgm', reverse_sql=migrations.RunSQL.noop),
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='category_name_search_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='product_name_search_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('sku'), name='gin_trgm_ops'), name='product_sku_search_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('description'), name='gin_trgm_ops'), name='product_desc_search_gin'),
        ),
    ]
