# Generated by Django 5.2.17 on 2026-09-29 19:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_category_category_name_search_gin_and_more'),
        ('sales', '0010_documentline_scan_generated'),
        ('shop', '0002_cartpackage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='identity_enforced',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_days',
            field=models.PositiveIntegerField(default=0, help_text='Default warranty in days; 0 means not specified.'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productunit',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='shop.orderitem'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='unit_id',
            field=models.CharField(editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Manufacturer serial'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.shipment'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='shipment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.shipmentitem'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='status',
            field=models.CharField(choices=[('REPAIR', 'Under repair'), ('SUPPLIER_RET', 'Returned to supplier'), ('WRITTEN_OFF', 'Written off'), ('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('FAULTY', 'Faulty'), ('RETURNED', 'Returned')], default='AVAILABLE', max_length=12),
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('MANUFACTURER', 'Manufacturer / alternate'), ('INTERNAL', 'Boforg')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barcodes', to='inventory.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(unique=True)),
                ('scope', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=120)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Counting'), ('REVIEW', 'Awaiting approval'), ('CLOSED', 'Approved')], default='OPEN', max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('approve_stocktake', 'Approve inventory reconciliation'), ('manage_unit_lifecycle', 'Manage unit lifecycle and after-sales'), ('print_inventory_labels', 'Print inventory labels')],
            },
        ),
        migrations.CreateModel(
            name='StocktakeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('outcome', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='inventory.stocktake')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=40)),
                ('previous_status', models.CharField(blank=True, max_length=12)),
                ('status', models.CharField(blank=True, max_length=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.invoice')),
                ('movement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stockmovement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_events', to='inventory.product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.productunit')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='UnitSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('warranty_expires', models.DateField(blank=True, null=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.invoice')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.documentline')),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.orderitem')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_history', to='inventory.productunit')),
            ],
            options={
                'ordering': ['-sold_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('inspection', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REPAIR', 'Repair'), ('CLOSED', 'Closed')], default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('replacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.productunit')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_cases', to='inventory.productunit')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unitsale')),
            ],
        ),
        migrations.CreateModel(
            name='StocktakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected', models.PositiveIntegerField(default=0)),
                ('counted', models.PositiveIntegerField(default=0)),
                ('expected_status', models.CharField(blank=True, max_length=12)),
                ('baseline_quantity', models.IntegerField(default=0)),
                ('baseline_reserved', models.IntegerField(default=0)),
                ('baseline_event_id', models.BigIntegerField(default=0)),
                ('baseline_movement_id', models.BigIntegerField(default=0)),
                ('decision', models.CharField(choices=[('REVIEW', 'Review'), ('KEEP', 'Keep records'), ('ADJUST', 'Apply count')], default='REVIEW', max_length=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.stocktake')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productunit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('unit__isnull', False)), fields=('session', 'unit'), name='stocktake_unique_unit'), models.UniqueConstraint(condition=models.Q(('unit__isnull', True)), fields=('session', 'product'), name='stocktake_unique_product')],
            },
        ),
    ]
