# Generated by Django 5.2.17 on 2026-09-29 19:42

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def backfill_identities(apps, schema_editor):
    Unit = apps.get_model('inventory', 'ProductUnit')
    Event = apps.get_model('inventory', 'UnitEvent')
    Sale = apps.get_model('inventory', 'UnitSale')
    from django.db.models import Count
    from django.db.models.functions import Upper, Trim
    duplicates = Unit.objects.exclude(serial_number__isnull=True).exclude(serial_number='').annotate(
        canonical=Upper(Trim('serial_number'))).exclude(canonical='').values('canonical').annotate(n=Count('pk')).filter(n__gt=1)
    if duplicates.exists():
        raise RuntimeError('Duplicate manufacturer serials after case/whitespace normalization. Review inventory identities before migrating; no serials were changed.')
    for unit in Unit.objects.select_related('sale_line__invoice__customer').iterator():
        unit.unit_id = f'BF-U-{unit.pk:09d}'
        if not (unit.serial_number or '').strip():
            unit.serial_number = None
        unit.save(update_fields=['unit_id', 'serial_number'])
        Event.objects.create(unit_id=unit.pk, product_id=unit.product_id, event='LEGACY_ID_ASSIGNED',
            status=unit.status, note='Boforg identity assigned; existing quantity, manufacturer serial and sale history preserved.')
        if unit.sale_line_id and unit.sold_at and unit.sale_line.invoice_id:
            Sale.objects.create(unit_id=unit.pk, invoice_id=unit.sale_line.invoice_id, line_id=unit.sale_line_id,
                customer_name=unit.sale_line.invoice.customer.name, unit_price=unit.sale_line.unit_price,
                unit_cost=unit.landed_cost, sold_at=unit.sold_at)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_product_identity_enforced_product_warranty_days_and_more'),
        ('sales', '0010_documentline_scan_generated'),
        ('shop', '0002_cartpackage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_identities),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper(django.db.models.functions.text.Trim('serial_number')), name='unit_manufacturer_serial_normalized_unique'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.CheckConstraint(condition=models.Q(('sale_line__isnull', True), ('order_item__isnull', True), _connector='OR'), name='unit_one_sale_assignment'),
        ),
    ]
