# Generated by Django 5.2.17 on 2026-09-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_productunit_unit_manufacturer_serial_normalized_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktakescan',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
