# Generated by Django 5.2.17 on 2026-09-10 17:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_category_department_combo_is_public_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='shop.cart')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.combo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cart', 'combo'), name='unique_cart_package')],
            },
        ),
    ]
