# Generated by Django 5.2.6 on 2025-09-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_currency_unique_per_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together=set(),
        ),
    ]
