# Generated by Django 5.2.6 on 2025-12-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_currency_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('PAYMENT', 'Payment'), ('BILL', 'Supplier Bill'), ('EXPENSE', 'Expense'), ('SHIPMENT', 'Shipment'), ('ADJUSTMENT', 'Adjustment')], default='ADJUSTMENT', max_length=20),
        ),
    ]
