# Generated by Django 5.2.17 on 2026-09-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_journalentry_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='submission_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
