# Generated by Django 5.2.17 on 2026-09-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_expense_attachment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='numbersequence',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'key'), name='unique_company_number_sequence'),
        ),
        migrations.AddConstraint(
            model_name='numbersequence',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('key',), name='unique_legacy_number_sequence'),
        ),
    ]
