# Generated by Django 5.2.17 on 2026-09-10 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_numbersequence_unique_company_number_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appayment',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='arpayment',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='supplierbill',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
