# Generated by Django 5.2.6 on 2025-09-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoiceitem_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
