# Generated by Django 5.2.6 on 2025-09-30 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_combo_comboitem'),
        ('sales', '0004_remove_quotationitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentline',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.combo'),
        ),
        migrations.DeleteModel(
            name='ComboItem',
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
    ]
