# Generated by Django 5.2.17 on 2026-09-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_invoice_stock_finalized_payment_submission_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='cost_unit_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=12, null=True),
        ),
    ]
