# Generated by Django 5.2.17 on 2026-09-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_invoice_date_alter_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='scan_generated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
